/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voy.me.pay.vision;

import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import voy.me.pay.control.ControllerCategoria;
import voy.me.pay.control.ControllerTipoTitulo;
import voy.me.pay.control.ControllerTitulo;
import voy.me.pay.entity.Categoria;
import voy.me.pay.entity.TipoTitulo;
import voy.me.pay.entity.Titulo;
import voy.me.pay.entity.to.TituloTableModel;

/**
 *
 * @author UnioestePROEX
 */
public class TelaTitulo extends javax.swing.JFrame {

    TituloTableModel tabelaTitulo = new TituloTableModel();
    
    List<Categoria> categorias = new ArrayList();
    List<TipoTitulo> tipoTitulos = new ArrayList();
    
    public TelaTitulo() throws ParseException {
        initComponents();
        
        jTitulos.setModel(tabelaTitulo);
        
        MaskFormatter maskRegistro = new MaskFormatter("##/##/####");  
        maskRegistro.install(jfDataRegistro);
        
        MaskFormatter maskVencimento = new MaskFormatter("##/##/####");        
        maskVencimento.install(jfVencimento);
        
        //botao listar categorias;
        ControllerCategoria c = new ControllerCategoria();
        categorias = c.listaCategorias();
        
        cbCategorias.addItem("Selecione");

        for (int i = 0; i < categorias.size(); i++) {
            cbCategorias.addItem(categorias.get(i).getNome());
        }
        
        //botao tipo de titulo
        ControllerTipoTitulo tTitulo = new ControllerTipoTitulo();
        tipoTitulos = tTitulo.listTipoTitulo();
        
        cbTipoTitulo.addItem("Selecione");
        for (int i = 0; i < tipoTitulos.size(); i++) {
            cbTipoTitulo.addItem(tipoTitulos.get(i).getNome());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtDesc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTitulos = new javax.swing.JTable();
        jtParcelas = new javax.swing.JTextField();
        jtNumeroTitulo = new javax.swing.JTextField();
        jtValor = new javax.swing.JTextField();
        jbSalvar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jfVencimento = new javax.swing.JFormattedTextField();
        jfDataRegistro = new javax.swing.JFormattedTextField();
        jcAtivo = new javax.swing.JComboBox<>();
        cbTipoTitulo = new javax.swing.JComboBox<>();
        jcSituacao1 = new javax.swing.JComboBox<>();
        cbCategorias = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtDesc.setBorder(javax.swing.BorderFactory.createTitledBorder("Descricao"));

        jTitulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTitulos);

        jtParcelas.setBorder(javax.swing.BorderFactory.createTitledBorder("Numero de Parcelas"));

        jtNumeroTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder("Numero do Título"));

        jtValor.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor"));

        jbSalvar.setText("Salvar");
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbExcluir.setText("Excluir");
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        jfVencimento.setBorder(javax.swing.BorderFactory.createTitledBorder("Vencimento"));

        jfDataRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Registro"));

        jcAtivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "Sim" }));
        jcAtivo.setBorder(javax.swing.BorderFactory.createTitledBorder("Ativo"));

        cbTipoTitulo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Título"));

        jcSituacao1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendente", "Liquidado" }));
        jcSituacao1.setBorder(javax.swing.BorderFactory.createTitledBorder("Situação"));

        cbCategorias.setBorder(javax.swing.BorderFactory.createTitledBorder("Categoria"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtDesc)
                                .addGap(13, 13, 13)
                                .addComponent(jfDataRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jfVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(296, 296, 296)
                                        .addComponent(jbSalvar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbEditar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbExcluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbSair))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(195, 195, 195)
                                        .addComponent(jtParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtNumeroTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(49, 49, 49))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addComponent(jcAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcSituacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTipoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfDataRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtNumeroTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jcAtivo)
                    .addComponent(cbTipoTitulo)
                    .addComponent(jcSituacao1)
                    .addComponent(cbCategorias))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalvar)
                    .addComponent(jbEditar)
                    .addComponent(jbExcluir)
                    .addComponent(jbSair))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        
        ControllerTitulo cTitulo = new ControllerTitulo();
        Titulo t = new Titulo();

        //ajusta o botao
        if (jbSalvar.getText().equals("Atualizar")) {
            jbSalvar.setText("Salvar");
        }

        //Obriga dos dados baseado no campo descricao
        if (jtDesc.getText().isEmpty()) {
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Insira os dados para Cadastrar!");

        } else {

            //Objeto Persistido: Coleta dados do abstract table para atualizar e persistir novamente;
            if (jTitulos.getSelectedRow() != -1) {

                int row = jTitulos.getSelectedRow();
                
                Object id = jTitulos.getValueAt(row, 0);
                t.setId((Long) id);
               
                t.setDescricao(jtDesc.getText());
                
                SimpleDateFormat dataRegistro = new SimpleDateFormat("dd/MM/yyyy");
                try {
                    t.setDataHoraCadastroTitulo(dataRegistro.parse(jfDataRegistro.getText()));
                } catch (ParseException ex) {
                    Component frame = null;
                    JOptionPane.showMessageDialog(frame, "Insira a data de Registro!");
                }
                
                SimpleDateFormat dataVencimento = new SimpleDateFormat("dd/MM/yyyy");
                try {
                    t.setDataVencimento((dataVencimento.parse(jfVencimento.getText())));
                } catch (ParseException ex){
                    Component frame = null;
                    JOptionPane.showMessageDialog(frame, "insira a data de Vencimento!");
                }
                
                t.setNumeroParcelaTitulo(Integer.parseInt(jtParcelas.getText()));
                t.setNumeroTitulo(Integer.parseInt(jtNumeroTitulo.getText()));
                
                t.setRegistroAtivoTitulo(jcAtivo.getSelectedIndex());
                
                if(jcAtivo.getSelectedIndex() == 0){
                    t.setStatus("Pendente");
                } else {
                    t.setStatus("Liquidado");
                }
                                                
                t.setValor(Float.parseFloat(jtValor.getText()));
                t.setCategoriaTitulo((String) cbTipoTitulo.getSelectedItem().toString());
                                                
                cTitulo.saveOrUpdate(t);
                tabelaTitulo.updateRow();

                //limpar campos;
                jtDesc.setText("");
                jfDataRegistro.setText("");
                jfVencimento.setText("");
                jtParcelas.setText("");
                jtNumeroTitulo.setText("");
                jtValor.setText("");
                jcAtivo.setSelectedIndex(0);
                cbTipoTitulo.setSelectedIndex(0);

            } else {

                //Objeto Novo: coleta dados do formulario para persistir o objeto;
                t.setDescricao(jtDesc.getText());
                
                SimpleDateFormat dataRegistro = new SimpleDateFormat("dd/MM/yyyy");
                try {
                    t.setDataHoraCadastroTitulo(dataRegistro.parse(jfDataRegistro.getText()));
                } catch (ParseException ex) {
                    Component frame = null;
                    JOptionPane.showMessageDialog(frame, "Insira a data de Registro!");
                }
                
                SimpleDateFormat dataVencimento = new SimpleDateFormat("dd/MM/yyyy");
                try {
                    t.setDataVencimento((dataVencimento.parse(jfVencimento.getText())));
                } catch (ParseException ex){
                    Component frame = null;
                    JOptionPane.showMessageDialog(frame, "insira a data de Vencimento!");
                }
                
                t.setNumeroParcelaTitulo(Integer.parseInt(jtParcelas.getText()));
                t.setNumeroTitulo(Integer.parseInt(jtNumeroTitulo.getText()));
                
                t.setRegistroAtivoTitulo(jcAtivo.getSelectedIndex());
                
                if(jcAtivo.getSelectedIndex() == 0){
                    t.setStatus("Pendente");
                } else {
                    t.setStatus("Liquidado");
                }
                                                
                t.setValor(Float.parseFloat(jtValor.getText()));
                t.setCategoriaTitulo(cbTipoTitulo.getSelectedItem().toString());

                //insere o objeto na tabela e já encaminha para persistencia;
                tabelaTitulo.addRow(cTitulo.saveOrUpdate(t));
                
                
                //Limpa os campos do formulario;
                jtDesc.setText("");
                jfDataRegistro.setText("");
                jfVencimento.setText("");
                jtParcelas.setText("");
                jtNumeroTitulo.setText("");
                jtValor.setText("");
                jcAtivo.setSelectedIndex(0);
                cbTipoTitulo.setSelectedIndex(0);
            }

        }
        
        
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        if (jTitulos.getSelectedRow() != -1) {

            jbSalvar.setText("Atualizar");

            int row = jTitulos.getSelectedRow();
            if (row > -1) {
                
                //coleta dados da tabela;
                Object descricao = jTitulos.getValueAt(row, 1);
                Object valor = jTitulos.getValueAt(row, 2).toString();
                Object vencimento = jTitulos.getValueAt(row, 3).toString();
                Object parcelas = jTitulos.getValueAt(row, 4).toString();
                Object numero = jTitulos.getValueAt(row, 5).toString();
                Object ativo = jTitulos.getValueAt(row, 6);
                Object situacao = jTitulos.getValueAt(row, 7);
                Object dataRegistro = jTitulos.getValueAt(row, 8).toString();
                Object categoriaTitulo = jTitulos.getValueAt(row, 9).toString();
                
                //insere as informaçoes nos campos
                jtDesc.setText((String) descricao);
                jtValor.setText((String) valor);
                jfVencimento.setText((String) vencimento);
                jtParcelas.setText((String) parcelas);
                jtNumeroTitulo.setText((String) numero);
                jfDataRegistro.setText((String) dataRegistro);
                
                //botao ativo
                if(ativo.equals("Não")){
                    jcAtivo.setSelectedIndex(0);
                } else {
                    jcAtivo.setSelectedIndex(1);
                }
                
                //botao situacao
                if(situacao.equals("Pendente")){
                    cbTipoTitulo.setSelectedIndex(0);
                } else {
                    cbTipoTitulo.setSelectedIndex(1);
                }
                
                //botao categoria
                cbTipoTitulo.setSelectedItem(categoriaTitulo);

            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Titulo para EDITAR!");
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
       
        ControllerTitulo t = new ControllerTitulo();

        if (jTitulos.getSelectedRow() != -1) {

            if (JOptionPane.showConfirmDialog(null, "Deseja excluir este cadastro?", "Atenção!",
                    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {

                int row = jTitulos.getSelectedRow();
                if (row > -1) {

                    //para selecionar o ID a coluna deve ser setada com valor 0;
                    //int column = jtCategorias.getSelectedColumn();
                    Object id = jTitulos.getValueAt(row, 0);

                    t.remove((Long) id);

                    tabelaTitulo.removeRow(jTitulos.getSelectedRow());

                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Selecione um titulo para Excluir!");
        }
        
    }//GEN-LAST:event_jbExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new TelaTitulo().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(TelaTitulo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCategorias;
    private javax.swing.JComboBox<String> cbTipoTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTitulos;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox<String> jcAtivo;
    private javax.swing.JComboBox<String> jcSituacao1;
    private javax.swing.JFormattedTextField jfDataRegistro;
    private javax.swing.JFormattedTextField jfVencimento;
    private javax.swing.JTextField jtDesc;
    private javax.swing.JTextField jtNumeroTitulo;
    private javax.swing.JTextField jtParcelas;
    private javax.swing.JTextField jtValor;
    // End of variables declaration//GEN-END:variables
}
